// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomFilterExample.proto

package com.hbase.learn.hbase_action.ch04;

public final class FilterProtosL {
  private FilterProtosL() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CustomFilterLOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string start_row = 1;
    /**
     * <code>required string start_row = 1;</code>
     */
    boolean hasStartRow();
    /**
     * <code>required string start_row = 1;</code>
     */
    java.lang.String getStartRow();
    /**
     * <code>required string start_row = 1;</code>
     */
    com.google.protobuf.ByteString
        getStartRowBytes();

    // required string end_row = 2;
    /**
     * <code>required string end_row = 2;</code>
     */
    boolean hasEndRow();
    /**
     * <code>required string end_row = 2;</code>
     */
    java.lang.String getEndRow();
    /**
     * <code>required string end_row = 2;</code>
     */
    com.google.protobuf.ByteString
        getEndRowBytes();
  }
  /**
   * Protobuf type {@code CustomFilterL}
   */
  public static final class CustomFilterL extends
      com.google.protobuf.GeneratedMessage
      implements CustomFilterLOrBuilder {
    // Use CustomFilterL.newBuilder() to construct.
    private CustomFilterL(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CustomFilterL(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CustomFilterL defaultInstance;
    public static CustomFilterL getDefaultInstance() {
      return defaultInstance;
    }

    public CustomFilterL getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CustomFilterL(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              startRow_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              endRow_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hbase.learn.hbase_action.ch04.FilterProtosL.internal_static_CustomFilterL_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hbase.learn.hbase_action.ch04.FilterProtosL.internal_static_CustomFilterL_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL.class, com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL.Builder.class);
    }

    public static com.google.protobuf.Parser<CustomFilterL> PARSER =
        new com.google.protobuf.AbstractParser<CustomFilterL>() {
      public CustomFilterL parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomFilterL(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CustomFilterL> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string start_row = 1;
    public static final int START_ROW_FIELD_NUMBER = 1;
    private java.lang.Object startRow_;
    /**
     * <code>required string start_row = 1;</code>
     */
    public boolean hasStartRow() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string start_row = 1;</code>
     */
    public java.lang.String getStartRow() {
      java.lang.Object ref = startRow_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          startRow_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string start_row = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStartRowBytes() {
      java.lang.Object ref = startRow_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startRow_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string end_row = 2;
    public static final int END_ROW_FIELD_NUMBER = 2;
    private java.lang.Object endRow_;
    /**
     * <code>required string end_row = 2;</code>
     */
    public boolean hasEndRow() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string end_row = 2;</code>
     */
    public java.lang.String getEndRow() {
      java.lang.Object ref = endRow_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          endRow_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string end_row = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEndRowBytes() {
      java.lang.Object ref = endRow_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endRow_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      startRow_ = "";
      endRow_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStartRow()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndRow()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStartRowBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getEndRowBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStartRowBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getEndRowBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL)) {
        return super.equals(obj);
      }
      com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL other = (com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL) obj;

      boolean result = true;
      result = result && (hasStartRow() == other.hasStartRow());
      if (hasStartRow()) {
        result = result && getStartRow()
            .equals(other.getStartRow());
      }
      result = result && (hasEndRow() == other.hasEndRow());
      if (hasEndRow()) {
        result = result && getEndRow()
            .equals(other.getEndRow());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasStartRow()) {
        hash = (37 * hash) + START_ROW_FIELD_NUMBER;
        hash = (53 * hash) + getStartRow().hashCode();
      }
      if (hasEndRow()) {
        hash = (37 * hash) + END_ROW_FIELD_NUMBER;
        hash = (53 * hash) + getEndRow().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CustomFilterL}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterLOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hbase.learn.hbase_action.ch04.FilterProtosL.internal_static_CustomFilterL_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hbase.learn.hbase_action.ch04.FilterProtosL.internal_static_CustomFilterL_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL.class, com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL.Builder.class);
      }

      // Construct using com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        startRow_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        endRow_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hbase.learn.hbase_action.ch04.FilterProtosL.internal_static_CustomFilterL_descriptor;
      }

      public com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL getDefaultInstanceForType() {
        return com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL.getDefaultInstance();
      }

      public com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL build() {
        com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL buildPartial() {
        com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL result = new com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.startRow_ = startRow_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.endRow_ = endRow_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL) {
          return mergeFrom((com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL other) {
        if (other == com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL.getDefaultInstance()) return this;
        if (other.hasStartRow()) {
          bitField0_ |= 0x00000001;
          startRow_ = other.startRow_;
          onChanged();
        }
        if (other.hasEndRow()) {
          bitField0_ |= 0x00000002;
          endRow_ = other.endRow_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStartRow()) {
          
          return false;
        }
        if (!hasEndRow()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hbase.learn.hbase_action.ch04.FilterProtosL.CustomFilterL) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string start_row = 1;
      private java.lang.Object startRow_ = "";
      /**
       * <code>required string start_row = 1;</code>
       */
      public boolean hasStartRow() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string start_row = 1;</code>
       */
      public java.lang.String getStartRow() {
        java.lang.Object ref = startRow_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          startRow_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string start_row = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStartRowBytes() {
        java.lang.Object ref = startRow_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          startRow_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string start_row = 1;</code>
       */
      public Builder setStartRow(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        startRow_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string start_row = 1;</code>
       */
      public Builder clearStartRow() {
        bitField0_ = (bitField0_ & ~0x00000001);
        startRow_ = getDefaultInstance().getStartRow();
        onChanged();
        return this;
      }
      /**
       * <code>required string start_row = 1;</code>
       */
      public Builder setStartRowBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        startRow_ = value;
        onChanged();
        return this;
      }

      // required string end_row = 2;
      private java.lang.Object endRow_ = "";
      /**
       * <code>required string end_row = 2;</code>
       */
      public boolean hasEndRow() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string end_row = 2;</code>
       */
      public java.lang.String getEndRow() {
        java.lang.Object ref = endRow_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          endRow_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string end_row = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEndRowBytes() {
        java.lang.Object ref = endRow_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endRow_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string end_row = 2;</code>
       */
      public Builder setEndRow(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        endRow_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string end_row = 2;</code>
       */
      public Builder clearEndRow() {
        bitField0_ = (bitField0_ & ~0x00000002);
        endRow_ = getDefaultInstance().getEndRow();
        onChanged();
        return this;
      }
      /**
       * <code>required string end_row = 2;</code>
       */
      public Builder setEndRowBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        endRow_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CustomFilterL)
    }

    static {
      defaultInstance = new CustomFilterL(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CustomFilterL)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomFilterL_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CustomFilterL_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031CustomFilterExample.proto\"3\n\rCustomFil" +
      "terL\022\021\n\tstart_row\030\001 \002(\t\022\017\n\007end_row\030\002 \002(\t" +
      "B:\n!com.hbase.learn.hbase_action.ch04B\rF" +
      "ilterProtosLH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CustomFilterL_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CustomFilterL_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CustomFilterL_descriptor,
              new java.lang.String[] { "StartRow", "EndRow", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
