// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomEndPoint.proto

package com.hbase.learn.hbase_action.ch04;

public final class RowSumProtos {
  private RowSumProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RowSumRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string start_key = 1;
    /**
     * <code>required string start_key = 1;</code>
     */
    boolean hasStartKey();
    /**
     * <code>required string start_key = 1;</code>
     */
    java.lang.String getStartKey();
    /**
     * <code>required string start_key = 1;</code>
     */
    com.google.protobuf.ByteString
        getStartKeyBytes();

    // required string end_key = 2;
    /**
     * <code>required string end_key = 2;</code>
     */
    boolean hasEndKey();
    /**
     * <code>required string end_key = 2;</code>
     */
    java.lang.String getEndKey();
    /**
     * <code>required string end_key = 2;</code>
     */
    com.google.protobuf.ByteString
        getEndKeyBytes();

    // required string family = 3;
    /**
     * <code>required string family = 3;</code>
     */
    boolean hasFamily();
    /**
     * <code>required string family = 3;</code>
     */
    java.lang.String getFamily();
    /**
     * <code>required string family = 3;</code>
     */
    com.google.protobuf.ByteString
        getFamilyBytes();

    // required string quailty = 4;
    /**
     * <code>required string quailty = 4;</code>
     */
    boolean hasQuailty();
    /**
     * <code>required string quailty = 4;</code>
     */
    java.lang.String getQuailty();
    /**
     * <code>required string quailty = 4;</code>
     */
    com.google.protobuf.ByteString
        getQuailtyBytes();
  }
  /**
   * Protobuf type {@code RowSumRequest}
   */
  public static final class RowSumRequest extends
      com.google.protobuf.GeneratedMessage
      implements RowSumRequestOrBuilder {
    // Use RowSumRequest.newBuilder() to construct.
    private RowSumRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RowSumRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RowSumRequest defaultInstance;
    public static RowSumRequest getDefaultInstance() {
      return defaultInstance;
    }

    public RowSumRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RowSumRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              startKey_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              endKey_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              family_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              quailty_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hbase.learn.hbase_action.ch04.RowSumProtos.internal_static_RowSumRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hbase.learn.hbase_action.ch04.RowSumProtos.internal_static_RowSumRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest.class, com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<RowSumRequest> PARSER =
        new com.google.protobuf.AbstractParser<RowSumRequest>() {
      public RowSumRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RowSumRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RowSumRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string start_key = 1;
    public static final int START_KEY_FIELD_NUMBER = 1;
    private java.lang.Object startKey_;
    /**
     * <code>required string start_key = 1;</code>
     */
    public boolean hasStartKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string start_key = 1;</code>
     */
    public java.lang.String getStartKey() {
      java.lang.Object ref = startKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          startKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string start_key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStartKeyBytes() {
      java.lang.Object ref = startKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string end_key = 2;
    public static final int END_KEY_FIELD_NUMBER = 2;
    private java.lang.Object endKey_;
    /**
     * <code>required string end_key = 2;</code>
     */
    public boolean hasEndKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string end_key = 2;</code>
     */
    public java.lang.String getEndKey() {
      java.lang.Object ref = endKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          endKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string end_key = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEndKeyBytes() {
      java.lang.Object ref = endKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string family = 3;
    public static final int FAMILY_FIELD_NUMBER = 3;
    private java.lang.Object family_;
    /**
     * <code>required string family = 3;</code>
     */
    public boolean hasFamily() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string family = 3;</code>
     */
    public java.lang.String getFamily() {
      java.lang.Object ref = family_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          family_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string family = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFamilyBytes() {
      java.lang.Object ref = family_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        family_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string quailty = 4;
    public static final int QUAILTY_FIELD_NUMBER = 4;
    private java.lang.Object quailty_;
    /**
     * <code>required string quailty = 4;</code>
     */
    public boolean hasQuailty() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string quailty = 4;</code>
     */
    public java.lang.String getQuailty() {
      java.lang.Object ref = quailty_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          quailty_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string quailty = 4;</code>
     */
    public com.google.protobuf.ByteString
        getQuailtyBytes() {
      java.lang.Object ref = quailty_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        quailty_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      startKey_ = "";
      endKey_ = "";
      family_ = "";
      quailty_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStartKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFamily()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQuailty()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStartKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getEndKeyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getFamilyBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getQuailtyBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStartKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getEndKeyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getFamilyBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getQuailtyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RowSumRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hbase.learn.hbase_action.ch04.RowSumProtos.internal_static_RowSumRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hbase.learn.hbase_action.ch04.RowSumProtos.internal_static_RowSumRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest.class, com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest.Builder.class);
      }

      // Construct using com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        startKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        endKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        family_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        quailty_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hbase.learn.hbase_action.ch04.RowSumProtos.internal_static_RowSumRequest_descriptor;
      }

      public com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest getDefaultInstanceForType() {
        return com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest.getDefaultInstance();
      }

      public com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest build() {
        com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest buildPartial() {
        com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest result = new com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.startKey_ = startKey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.endKey_ = endKey_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.family_ = family_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.quailty_ = quailty_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest) {
          return mergeFrom((com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest other) {
        if (other == com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest.getDefaultInstance()) return this;
        if (other.hasStartKey()) {
          bitField0_ |= 0x00000001;
          startKey_ = other.startKey_;
          onChanged();
        }
        if (other.hasEndKey()) {
          bitField0_ |= 0x00000002;
          endKey_ = other.endKey_;
          onChanged();
        }
        if (other.hasFamily()) {
          bitField0_ |= 0x00000004;
          family_ = other.family_;
          onChanged();
        }
        if (other.hasQuailty()) {
          bitField0_ |= 0x00000008;
          quailty_ = other.quailty_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStartKey()) {
          
          return false;
        }
        if (!hasEndKey()) {
          
          return false;
        }
        if (!hasFamily()) {
          
          return false;
        }
        if (!hasQuailty()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string start_key = 1;
      private java.lang.Object startKey_ = "";
      /**
       * <code>required string start_key = 1;</code>
       */
      public boolean hasStartKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string start_key = 1;</code>
       */
      public java.lang.String getStartKey() {
        java.lang.Object ref = startKey_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          startKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string start_key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStartKeyBytes() {
        java.lang.Object ref = startKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          startKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string start_key = 1;</code>
       */
      public Builder setStartKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        startKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string start_key = 1;</code>
       */
      public Builder clearStartKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        startKey_ = getDefaultInstance().getStartKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string start_key = 1;</code>
       */
      public Builder setStartKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        startKey_ = value;
        onChanged();
        return this;
      }

      // required string end_key = 2;
      private java.lang.Object endKey_ = "";
      /**
       * <code>required string end_key = 2;</code>
       */
      public boolean hasEndKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string end_key = 2;</code>
       */
      public java.lang.String getEndKey() {
        java.lang.Object ref = endKey_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          endKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string end_key = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEndKeyBytes() {
        java.lang.Object ref = endKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string end_key = 2;</code>
       */
      public Builder setEndKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        endKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string end_key = 2;</code>
       */
      public Builder clearEndKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        endKey_ = getDefaultInstance().getEndKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string end_key = 2;</code>
       */
      public Builder setEndKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        endKey_ = value;
        onChanged();
        return this;
      }

      // required string family = 3;
      private java.lang.Object family_ = "";
      /**
       * <code>required string family = 3;</code>
       */
      public boolean hasFamily() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string family = 3;</code>
       */
      public java.lang.String getFamily() {
        java.lang.Object ref = family_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          family_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string family = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFamilyBytes() {
        java.lang.Object ref = family_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          family_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string family = 3;</code>
       */
      public Builder setFamily(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        family_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string family = 3;</code>
       */
      public Builder clearFamily() {
        bitField0_ = (bitField0_ & ~0x00000004);
        family_ = getDefaultInstance().getFamily();
        onChanged();
        return this;
      }
      /**
       * <code>required string family = 3;</code>
       */
      public Builder setFamilyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        family_ = value;
        onChanged();
        return this;
      }

      // required string quailty = 4;
      private java.lang.Object quailty_ = "";
      /**
       * <code>required string quailty = 4;</code>
       */
      public boolean hasQuailty() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string quailty = 4;</code>
       */
      public java.lang.String getQuailty() {
        java.lang.Object ref = quailty_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          quailty_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string quailty = 4;</code>
       */
      public com.google.protobuf.ByteString
          getQuailtyBytes() {
        java.lang.Object ref = quailty_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          quailty_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string quailty = 4;</code>
       */
      public Builder setQuailty(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        quailty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string quailty = 4;</code>
       */
      public Builder clearQuailty() {
        bitField0_ = (bitField0_ & ~0x00000008);
        quailty_ = getDefaultInstance().getQuailty();
        onChanged();
        return this;
      }
      /**
       * <code>required string quailty = 4;</code>
       */
      public Builder setQuailtyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        quailty_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RowSumRequest)
    }

    static {
      defaultInstance = new RowSumRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RowSumRequest)
  }

  public interface RowSumResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 rowSum = 1;
    /**
     * <code>optional int64 rowSum = 1;</code>
     */
    boolean hasRowSum();
    /**
     * <code>optional int64 rowSum = 1;</code>
     */
    long getRowSum();
  }
  /**
   * Protobuf type {@code RowSumResponse}
   */
  public static final class RowSumResponse extends
      com.google.protobuf.GeneratedMessage
      implements RowSumResponseOrBuilder {
    // Use RowSumResponse.newBuilder() to construct.
    private RowSumResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RowSumResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RowSumResponse defaultInstance;
    public static RowSumResponse getDefaultInstance() {
      return defaultInstance;
    }

    public RowSumResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RowSumResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rowSum_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hbase.learn.hbase_action.ch04.RowSumProtos.internal_static_RowSumResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hbase.learn.hbase_action.ch04.RowSumProtos.internal_static_RowSumResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse.class, com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<RowSumResponse> PARSER =
        new com.google.protobuf.AbstractParser<RowSumResponse>() {
      public RowSumResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RowSumResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RowSumResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 rowSum = 1;
    public static final int ROWSUM_FIELD_NUMBER = 1;
    private long rowSum_;
    /**
     * <code>optional int64 rowSum = 1;</code>
     */
    public boolean hasRowSum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 rowSum = 1;</code>
     */
    public long getRowSum() {
      return rowSum_;
    }

    private void initFields() {
      rowSum_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, rowSum_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, rowSum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RowSumResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hbase.learn.hbase_action.ch04.RowSumProtos.internal_static_RowSumResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hbase.learn.hbase_action.ch04.RowSumProtos.internal_static_RowSumResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse.class, com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse.Builder.class);
      }

      // Construct using com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rowSum_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hbase.learn.hbase_action.ch04.RowSumProtos.internal_static_RowSumResponse_descriptor;
      }

      public com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse getDefaultInstanceForType() {
        return com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse.getDefaultInstance();
      }

      public com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse build() {
        com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse buildPartial() {
        com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse result = new com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rowSum_ = rowSum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse) {
          return mergeFrom((com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse other) {
        if (other == com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse.getDefaultInstance()) return this;
        if (other.hasRowSum()) {
          setRowSum(other.getRowSum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 rowSum = 1;
      private long rowSum_ ;
      /**
       * <code>optional int64 rowSum = 1;</code>
       */
      public boolean hasRowSum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 rowSum = 1;</code>
       */
      public long getRowSum() {
        return rowSum_;
      }
      /**
       * <code>optional int64 rowSum = 1;</code>
       */
      public Builder setRowSum(long value) {
        bitField0_ |= 0x00000001;
        rowSum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 rowSum = 1;</code>
       */
      public Builder clearRowSum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rowSum_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RowSumResponse)
    }

    static {
      defaultInstance = new RowSumResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RowSumResponse)
  }

  /**
   * Protobuf service {@code RowSumService}
   */
  public static abstract class RowSumService
      implements com.google.protobuf.Service {
    protected RowSumService() {}

    public interface Interface {
      /**
       * <code>rpc getRowSum(.RowSumRequest) returns (.RowSumResponse);</code>
       */
      public abstract void getRowSum(
          com.google.protobuf.RpcController controller,
          com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest request,
          com.google.protobuf.RpcCallback<com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new RowSumService() {
        @java.lang.Override
        public  void getRowSum(
            com.google.protobuf.RpcController controller,
            com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest request,
            com.google.protobuf.RpcCallback<com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse> done) {
          impl.getRowSum(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getRowSum(controller, (com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getRowSum(.RowSumRequest) returns (.RowSumResponse);</code>
     */
    public abstract void getRowSum(
        com.google.protobuf.RpcController controller,
        com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest request,
        com.google.protobuf.RpcCallback<com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.hbase.learn.hbase_action.ch04.RowSumProtos.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getRowSum(controller, (com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest)request,
            com.google.protobuf.RpcUtil.<com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getRowSum(
          com.google.protobuf.RpcController controller,
          com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest request,
          com.google.protobuf.RpcCallback<com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse.class,
            com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse getRowSum(
          com.google.protobuf.RpcController controller,
          com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse getRowSum(
          com.google.protobuf.RpcController controller,
          com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.hbase.learn.hbase_action.ch04.RowSumProtos.RowSumResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:RowSumService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RowSumRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RowSumRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RowSumResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RowSumResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024CustomEndPoint.proto\"T\n\rRowSumRequest\022" +
      "\021\n\tstart_key\030\001 \002(\t\022\017\n\007end_key\030\002 \002(\t\022\016\n\006f" +
      "amily\030\003 \002(\t\022\017\n\007quailty\030\004 \002(\t\" \n\016RowSumRe" +
      "sponse\022\016\n\006rowSum\030\001 \001(\0032=\n\rRowSumService\022" +
      ",\n\tgetRowSum\022\016.RowSumRequest\032\017.RowSumRes" +
      "ponseB6\n!com.hbase.learn.hbase_action.ch" +
      "04B\014RowSumProtosH\001\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RowSumRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RowSumRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RowSumRequest_descriptor,
              new java.lang.String[] { "StartKey", "EndKey", "Family", "Quailty", });
          internal_static_RowSumResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_RowSumResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RowSumResponse_descriptor,
              new java.lang.String[] { "RowSum", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
